import { Project, GeneratedOutputs, OutputFormat } from '../types';

export class AIEngine {
    /**
     * Simulates the AI generation process.
     * In a real app, this would call LLM APIs (OpenAI, Anthropic, etc.)
     * and use the Project's AgentConfig to tune the responses.
     */
    public async generateProjectOutput(project: Project, prompt: string): Promise<GeneratedOutputs> {
        console.log(`AI Engine: Generating ${project.outputFormat} output for project ${project.name}...`);
        
        // Simulate processing time based on enabled agents
        const processingTime = this.calculateProcessingTime(project);
        await new Promise(resolve => setTimeout(resolve, processingTime));

        const content = this.simulateAIResponse(project, prompt);
        
        return {
            fullHtml: this.wrapInHtml(content, project),
            markdown: this.convertToMarkdown(content),
            pdfHtml: this.convertToPdfHtml(content),
            custom: content,
            // Mocking base64 for PPTX
            pptx: project.outputFormat === 'ppt' ? 'BASE64_MOCK_PPTX_DATA' : undefined
        };
    }

    private calculateProcessingTime(project: Project): number {
        let time = 500;
        if (project.agents.knowledgeLearner.enabled) time += 1000;
        if (project.agents.webSearch.enabled) time += 1500;
        if (project.agents.dataAnalyst.enabled) time += 1000;
        return time;
    }

    private simulateAIResponse(project: Project, prompt: string): string {
        const agents = project.agents;
        let response = `[AI Response for: ${prompt}]

`;

        if (agents.knowledgeLearner.enabled) {
            response += `(KnowledgeLearner: Using knowledge base "${agents.knowledgeLearner.knowledgeBase}" to provide context...)
`;
        }
        if (agents.webSearch.enabled) {
            response += `(WebSearch: Searching latest trends and data from web...)
`;
        }
        if (agents.dataAnalyst.enabled) {
            response += `(DataAnalyst: Analyzing patterns using model ${agents.dataAnalyst.model} with temp ${agents.dataAnalyst.temperature}...)
`;
        }

        response += `
This is a simulated high-quality output for the project "${project.name}".
`;
        response += `The requested perspective on "${prompt}" has been synthesized using the configured AI pipeline.
`;
        response += `
Key Insights:
1. Optimized for ${project.outputFormat} format.
2. Aligned with system prompt: ${agents.answeringAgent.systemPrompt || 'Default assistant'}.
3. Validated for bias and hallucinations.`;

        return response;
    }

    private wrapInHtml(content: string, project: Project): string {
        return `
<!DOCTYPE html>
<html>
<head>
    <title>${project.name}</title>
    <style>
        body { font-family: sans-serif; line-height: 1.6; padding: 2rem; color: #333; max-width: 800px; margin: auto; }
        .header { border-bottom: 2px solid ${project.features.accentColorPicker ? '#c7794a' : '#ccc'}; margin-bottom: 1rem; }
        .content { white-space: pre-wrap; }
        .footer { margin-top: 2rem; font-size: 0.8rem; color: #666; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>${project.name}</h1>
        <p>${project.description}</p>
    </div>
    <div class="content">
        ${content}
    </div>
    <div class="footer">
        Generated by Perspective AI - ${new Date().toLocaleDateString()}
    </div>
</body>
</html>`;
    }

    private convertToMarkdown(content: string): string {
        return `# Perspective AI Output

${content}`;
    }

    private convertToPdfHtml(content: string): string {
        return `<div style="font-family: serif; padding: 40px;">${content}</div>`;
    }
}
